core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('src.website.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('accounts/', include('src.accounts.urls')),
                  path('business/', include('src.portal.business.urls')),
                  path('investor/', include('src.portal.investor.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portal/business/urls.py
from django.urls import path, include

from . import views

app_name = 'business'

urlpatterns = [
    path('dashboard/', views.BusinessDashboard.as_view(), name='dashboard'),
    path('project-list/', views.ProjectListView.as_view(), name='project_list'),
    path('project-detail<str:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('project-create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('project-update/<str:pk>/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('project-delete/<str:pk>/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<str:pk>/shares/', views.ProjectShareView.as_view(), name='project_share'),
    path('project-Shares-list/', views.SharesListView.as_view(), name='shares'),
    path('project-shares-update/<str:pk>/<str:project>/', views.ProjectShareUpdate.as_view(), name='shares_update'),
    path('project-share-delete/<str:pk>/<str:project>/', views.ProjectShareDelete.as_view(), name='shares_delete'),
    path('project-investors/', views.ShareInvestors.as_view(), name='project_investor'),
    path('investor-detail/<str:pk>', views.ShareInvestorDetailView.as_view(), name='investor_detail'),
    path('money-flow/<str:pk>/', views.MoneyFLowView.as_view(), name='money_flow'),
    path('payments/', views.PaymentListView.as_view(), name='payment')

]

src/portal/investor/urls.py
from django.urls import path, include

from . import views
from .views import SuccessPayment, CancelPayment

app_name = 'investor'

urlpatterns = [
    path('dashboard/', views.InvestorDashboard.as_view(), name='dashboard'),
    path('project-list/',views.ProjectListView.as_view(), name='project_list'),
    path('buy-share/<str:pk>/',views.BuyShareView.as_view(), name='buy_share'),
    path('view-share/<str:pk>/',views.ViewShareDetail.as_view(), name='view_share'),
    path('share_detail/',views.ShareDetailView.as_view(), name='share_detail'),
    path('project/<str:pk>/shares/', views.SellShareView.as_view(), name='investor_shares'),
    path('company-detail/<str:pk>/', views.CompanyDetailView.as_view(), name='company_detail'),
    path('project-detail/<str:pk>/', views.ProjectInvestorDetailView.as_view(), name='project_detail'),
    path('payment-success/', SuccessPayment.as_view(), name="success"),
    path('payment-cancelled/', CancelPayment.as_view(), name="cancel"),


    

]

templates/core/include/business_header.html
{% load static %}

<li class="nav-item">
    <a class="nav-link" href="/">
        <i class="bx bxs-home mr-2"></i>Home
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'business:dashboard' %}">
        <i class="bx bx-sitemap mr-2"></i>Dashboard
    </a>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button"
       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="bx bx-collection mr-2"></i>Project
        <div class="arrow-down"></div>
    </a>
    <div class="dropdown-menu" aria-labelledby="topnav-components">
        <a href="{% url 'business:project_create' %}" class="dropdown-item">Add Project</a>
        <a href="{% url 'business:project_list' %}" class="dropdown-item">Projects</a>
        <a href="{% url 'business:shares' %}" class="dropdown-item">Shares</a>
    </div>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'business:project_investor' %}">
        <i class="bx bx-briefcase mr-2"></i>Investors
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'business:payment' %}">
        <i class="fa fa-credit-card mr-2"></i>Payments
    </a>
</li>


{# ------------------------------------------------------------------------------------------------------------------ #}

templates/core/include/footer.html
 {% load static %}
 <!-- Footer Section Starts Here -->
    <footer class="footer-section section-bg">
        <div class="footer-top padding-top pb-5 border-bottom border--white">
            <div class="container">
                <div class="row gy-5 justify-content-md-between">
                    <div class="col-xl-10 col-lg-10 col-sm-10">
                        <div class="footer__widget">
                            <h3 class="widget-title">About Company</h3>
                            <p>Aliquam orci a nullam tempor sapien  graonec enim ipsum porta justo velna an auctor undo congue magna laoreet augue sapien</p>
                            <ul class="social-links">
                                <li><a class="facebook-bg" href="#0"><i class="lab la-facebook-f"></i></a></li>
                                <li><a class="twitter-bg" href="#0"><i class="lab la-twitter"></i></a></li>
                                <li><a class="instagram-bg" href="#0"><i class="lab la-instagram"></i></a></li>
                                <li><a class="pinterest-bg" href="#0"><i class="lab la-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    
        </div>
        <div class="footer-bottom">
            <div class="container">
                <p class="copyright text-center py-3">
                    Copyright &copy; 2021 All Rights Reserved.
                </p>
            </div>
        </div>
    </footer>
    <!-- Footer Section Ends Here -->

templates/core/include/header.html
{% load static %}
    <div class="preloader">
        <div class="preinnner">
            <div class="ring"></div>
            <div class="ring"></div>
            <div class="ring"></div>
        </div>
    </div>
    <div class="overlay"></div>

    <!-- Header Section Starts Here -->
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="header__top__wrapper d-flex flex-wrap align-items-center justify-content-center justify-content-md-between text-center">
                    <ul class="contacts d-flex flex-wrap justify-content-center">
                        <li><a href="https://template.viserlab.com/cdn-cgi/l/email-protection#6004050d0f20070d01090c4e030f0d"><i class="las la-envelope-open"></i> <span class="__cf_email__" data-cfemail="f195949c9eb1969c90989ddf929e9c">[email&#160;protected]</span></a></li>
                        <li><a href="tel:129075"><i class="las la-phone-volume"></i> 123  -  456  -  7890</a></li>
                    </ul>
                    <div class="right__area d-flex flex-wrap align-items-center mt-3 mt-md-0">
                        <select name="language" class="nice-select custom--scrollbar">
                            <option>English</option>
                        </select>
                        <a href="dashboard.html" class="user__thumb ms-3 me-3 me-lg-0">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container">
                <div class="header-bottom-area">
                    <div class="logo"><a href="index.html"><img src="{% static 'website/images/logo.png' %}" alt="logo"></a></div>
                    <ul class="menu">
                        <li>
                            <a href="#0">Home</a>
                        </li>
                        
                        
              
                    </ul>   <!-- Menu End -->
                    {% if user.is_authenticated %}
                        {% if user.is_business %}
                        <a href="{% url 'business:dashboard'%}" class="cmn--btn">Dashboard</a>
                        {% elif user.is_investor %}
                        <a href="{% url 'investor:dashboard'%}" class="cmn--btn">Dashboard</a>                        {% endif %}
                    {% else %}
                    <div class="button__wrapper d-none d-lg-block">
                        <a href="{% url 'account_signup' %}" class="cmn--btn">Register</a>
                        <a href="{% url 'account_login'%}" class="cmn--btn">Login</a>
                    </div>
                    {% endif %}
                    
    
                    <div class="header-trigger-wrapper d-flex d-lg-none align-items-center">
                        <div class="mobile-nav-right d-flex align-items-center"></div>
                        <a href="#0" class="search--btn me-4 text--base"><i class="fas fa-search"></i></a>
                        <div class="header-trigger d-block d--none">
                            <span></span>
                        </div>
                    </div>  <!-- Trigger End-->
                </div>
            </div>
        </div>
    </div>
    <!-- Header Section Ends Here -->

    <!-- Search Form Ends Here -->

templates/core/include/investor_header.html
{% load static %}

<li class="nav-item">
    <a class="nav-link" href="/">
        <i class="bx bxs-home mr-2"></i>Home
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'investor:dashboard' %}">
        <i class="bx bx-sitemap mr-2"></i>Dashboard
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'investor:project_list' %}">
        <i class="bx bx-globe mr-2"></i>Projects
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'investor:share_detail' %}">
        <i class="bx bx-briefcase mr-2"></i>Shares
    </a>
</li>


{# ------------------------------------------------------------------------------------------------------------------ #}

templates/core/include/messages.html
<div>
    {% if messages %}
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'debug' %}
                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
</div>
