core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('src.website.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('accounts/', include('src.accounts.urls')),
                  path('business/', include('src.portal.business.urls')),
                  path('investor/', include('src.portal.investor.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portal/investor/urls.py
from django.urls import path, include

from . import views
from .views import SuccessPayment, CancelPayment

app_name = 'investor'

urlpatterns = [
    path('dashboard/', views.InvestorDashboard.as_view(), name='dashboard'),
    path('project-list/',views.ProjectListView.as_view(), name='project_list'),
    path('buy-share/<str:pk>/',views.BuyShareView.as_view(), name='buy_share'),
    path('view-share/<str:pk>/',views.ViewShareDetail.as_view(), name='view_share'),
    path('share_detail/',views.ShareDetailView.as_view(), name='share_detail'),
    path('project/<str:pk>/shares/', views.SellShareView.as_view(), name='investor_shares'),
    path('company-detail/<str:pk>/', views.CompanyDetailView.as_view(), name='company_detail'),
    path('project-detail/<str:pk>/', views.ProjectInvestorDetailView.as_view(), name='project_detail'),
    path('payment-success/', SuccessPayment.as_view(), name="success"),
    path('payment-cancelled/', CancelPayment.as_view(), name="cancel"),


    

]

src/portal/investor/models.py
from django.db import models

# Create your models here.

src/portal/investor/views.py
import stripe
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, TemplateView, CreateView, UpdateView, DetailView
from .form import BuyShareForm, SellShareForm
from src.accounts.decorators import investor_required
from src.portal.business.models import Business, Project, Investor, Shares, Project_Investor, InvestorShare, Payment
from src.portal.investor.bll import money_flow
from ..business.filter import ProjectFilter, ProjectShareFilter


@method_decorator(investor_required, name='dispatch')
class InvestorDashboard(TemplateView):
    template_name = 'investor/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(InvestorDashboard, self).get_context_data(**kwargs)
        project = Project.objects.all()
        share = Shares.objects.all()
        business_profit_project, business_loss_project, investor_profit, investor_loss = money_flow(self,
                                                                                                    request=self.request)

        project_investor = Project_Investor.objects.all()
        context['applied_project'] = project_investor.count()
        context['project_count'] = project.count()
        context['project_list'] = Project.objects.all()

        context['investor_profit'] = investor_profit

        context['object_list'] = Project_Investor.objects.filter(investor__user=self.request.user, value__gt=0).all()[
                                 :10]
        return context


@method_decorator(investor_required, name='dispatch')
class ProjectListView(ListView):
    model = Shares
    template_name = 'investor/project_list.html'

    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        object_list = Shares.objects.filter(value__gt=0)
        filter_form = ProjectShareFilter(self.request.GET, object_list)
        context['form'] = filter_form.form
        context['object_list'] = filter_form.qs
        return context


stripe.api_key = 'sk_test_51LC794Js59MkLRK8jKm97MecFP4dwcOrxfetIXefvByCaodNGQ1qNdKqaxVBZGD1aW9VTBh69W73T1Ox7LtByRpy00nRXonBff '


@method_decorator(investor_required, name='dispatch')
class BuyShareView(View):
    def get(self, request, pk, *args, **kwargs):
        form = BuyShareForm
        return render(request, 'investor/buy_share.html')

    def post(self, request, pk, *args, **kwargs):

        form = BuyShareForm(request.POST)
        user_value = self.request.POST.get('value')
        host = self.request.get_host()
        share = Shares.objects.get(id=pk)
        share_equity = share.percentage_equity
        share_value = share.value
        user_percentage = (int(user_value) / share_value) * 100
        user_equity = (float(user_percentage) * float(share_equity)) / 100
        price = int(user_value)
        user = request.user
        investor = Investor.objects.get(user=self.request.user)
        if int(user_value) <= int(share.value):
            customer = stripe.Customer.create(
                name=self.request.user.username,
                email=self.request.user.email
            )
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                customer=customer,
                submit_type='pay',
                line_items=[
                    {
                        'price_data': {
                            'currency': 'usd',
                            'unit_amount': price * 100,
                            'product_data': {
                                'name': f'Sending Money To {share.project.business}',
                            },
                        },
                        'quantity': 1,
                    },
                ],

                mode='payment',
                success_url='http://' + host + reverse('investor:success') \
                            + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url='http://{}{}'.format(host, reverse(
                    'investor:cancel')),
                client_reference_id=self.kwargs['pk']
            )
            return redirect(checkout_session.url, code=303)


        else:
            messages.error(request, 'Enter a value less than or equall to')
            return redirect('investor:buy_share', pk)


class SuccessPayment(View):
    def get(self, *args, **kwargs):
        session = stripe.checkout.Session.retrieve(self.request.GET['session_id'])
        payment_id = session.payment_intent
        pk = session.client_reference_id
        share = Shares.objects.get(id=pk)
        investor = Investor.objects.get(user=self.request.user)
        u_value = session.amount_total
        user_value = int(u_value / 100)

        share_equity = float(share.percentage_equity)
        share_value = share.value
        user_percentage = (int(user_value) / share_value) * 100
        user_equity = (float(user_percentage) * float(share_equity)) / 100
        project_investor, create = Project_Investor.objects.get_or_create(share=share, investor=investor)
        project_investor.value = int(project_investor.value) + int(user_value)
        project_investor.percentage_equity = float(project_investor.percentage_equity) + float(user_equity)
        project_investor.is_agree = True
        project_investor.save()
        payment = Payment(
            payment_id=payment_id,
            project_investor=project_investor,
            amount=user_value
        )
        share.value = int(share_value) - int(user_value)
        share.percentage_equity = float(share_equity) - float(user_equity)
        share.sell_equity = float(share.sell_equity) + float(user_equity)
        payment.save()
        share.save()
        return render(self.request, 'investor/success.html')


class CancelPayment(TemplateView):
    template_name = 'investor/cancel.html'


@method_decorator(investor_required, name='dispatch')
class ShareDetailView(ListView):
    model = Project_Investor
    template_name = 'investor/share_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ShareDetailView, self).get_context_data(**kwargs)
        context['object_list'] = Project_Investor.objects.filter(investor__user=self.request.user)
        return context


@method_decorator(investor_required, name='dispatch')
class ViewShareDetail(DetailView):
    model = Project_Investor
    template_name = 'investor/share_view_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ViewShareDetail, self).get_context_data(**kwargs)
        p_i = self.get_object()
        return context


@method_decorator(investor_required, name='dispatch')
class SellShareView(View):

    def get(self, request, pk, *args, **kwargs):
        form = SellShareForm
        return render(request, 'investor/sell_share.html')

    def post(self, request, pk, *args, **kwargs):

        # GET: required values
        form = SellShareForm(request.POST)
        user_value = self.request.POST.get('value')
        user_equity = self.request.POST.get('percentage')

        # GET: share model values
        share = Project_Investor.objects.get(id=pk)
        investor_share_equity = share.percentage_equity
        investor_share_value = share.value
        # CAL1: user calculations
        user_percentage = (int(user_value) / investor_share_value) * 100
        user_equity = (float(user_equity) * float(investor_share_equity)) / 100

        if int(user_value) <= int(share.value):
            project_investor, created = InvestorShare.objects.get_or_create(project_investor=share)
            project_investor.value = int(project_investor.value) + int(user_value)
            project_investor.percentage_equity = int(project_investor.percentage_equity) + int(user_equity)
            project_investor.save()

            # project_inv.save()
            share.value = int(investor_share_value) - int(user_value)
            share.percentage_equity = float(investor_share_equity) - float(user_equity)
            share.save()

            return redirect('investor:dashboard')
        else:
            messages.error(request, 'Enter a value less than or equall to')
            return redirect('investor:sell_share', pk)


@method_decorator(investor_required, name='dispatch')
class ProjectInvestorDetailView(DetailView):
    model = Project
    context_object_name = 'object'
    template_name = 'investor/project_detail.html'


class CompanyDetailView(DetailView):
    model = Project_Investor
    context_object_name = 'object'
    template_name = 'investor/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        business = Business.objects.filter(id=self.kwargs['pk'])
        context['projects'] = business
        return context

src/portal/investor/templates/investor/buy_share.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}

<div class="col-xl-10 col-sm-9">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label >Value</label>
          <input name="value" type="number" class="form-control"  placeholder="Enter Value">
        </div> 
        <div class="form-group">
            <p>Must check if the business is registered with security and exchange commission </br>of Pakistan (<a href="#">https://eservices.secp.gov.pk/eServices/ControllerServlet</a>).
                Before you buy it, </br>contact the company via their email address or phone to make 	</br>sure, if it’s the actual company which is selling the share.</br>
                By signing this you agree to:</br>
                if the company is fraud BuisnessChain is not responsible.
                </p>
        </div>     
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="is_agree" id="checkbox" required>
            <label class="form-check-label" for="flexCheckDefault">
              Agree
            </label>
          </div>  
        <div class="col-sm-6">
            <div class="text-sm-right">
                <button type="submit" class="btn btn-danger">
                    <i class="mdi mdi-check mr-1"></i> <a href="{% url 'investor:project_list' %}">Cancel</a>
                </button>
                <button type="submit" class="btn btn-success">
                    <i class="mdi mdi-check mr-1"></i> Buy Share
                </button>
            </div>
        </div>
      </form>
        <div class="row my-4">
            <div class="col-sm-6">
                <a href="{% url 'investor:dashboard' %}"
                   class="btn text-muted d-none d-sm-inline-block btn-link">
                    <i class="mdi mdi-arrow-left mr-1"></i> My Applications </a>
            </div>

            
        </div>
    </form>
</div>

</div>
</form>
</div>

{% endblock content %}

src/portal/investor/templates/investor/cancel.html
payment cancel

src/portal/investor/templates/investor/dashboard.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">

{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class="fa fa-clipboard-list h2 text-dark mb-0"></i>
                    </div>
                    <div class="media-body">
                        <p class="text-muted mb-2">Available Projects </p>
                        <h5 class="mb-0">
                            {{ project_count }}
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class="fa fa-pen h2 text-primary mb-0"></i>
                    </div>
                    <div class="media-body">
                        <p class="text-muted mb-2">Applied Projects</p>
                        <h5 class="mb-0">
                            {{ applied_project }}
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class="fa fa-clock h2 text-primary mb-0"></i>
                    </div>
                    <div class="media-body">
                        <p class="text-muted mb-2">Profit</p>
                        <h5 class="mb-0">
                         {{investor_profit}}
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <!-- <div class="col-sm-3">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class="fa fa-check-circle h2 text-success mb-0"></i>
                    </div>
                    <div class="media-body">
                        <p class="text-muted mb-2">Accepted</p>
                        <h5 class="mb-0">
                            {{ application_acc_count }}
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
</div>

 
<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-body">
                {% if object_list %}

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-hover">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Business Name</th>
                            <th scope="col">Project Name</th>
                            <th scope="col">Buyed Share</th>
                            <th scope="col">Buyed Equity</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                                <p class="mb-0">
                                    <b><a href="{% url 'investor:company_detail' object.pk %}">{{ object.share.project.business }}</a></b>
                                </p>
                            </td>
                            <td>
                                <p class="mb-0">
                                    <b><a href="{% url 'investor:project_detail' object.share.project.pk %}">{{ object.share.project }}</a></b>
                                </p>
                            </td>

                            <td>
                                <p class="mb-0">
                                    <b><a href="#">{{ object.value }}</a>
                                    </b>
                            </td>
                            <td>
                                <p class="mb-0">
                                    <b><a href="#">{{ object.percentage_equity }}</a>
                                    </b>
                            </td>

                            <td>
                                <p class="mb-0">
                                    <a href="{% url 'investor:view_share' object.pk %}"
                                       class="btn btn-success btn-sm">view</a>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                {% else %}
                <p class="text-danger">
                    <b><i class="fa fa-exclamation-circle"></i> No Project found.</b>
                </p>
                {% endif %}

            </div>
        </div>
        <!-- <div class="col-sm-6">
            <a href=""
               class="btn text-muted d-none d-sm-inline-block btn-link">
                <i class="mdi mdi-arrow-left mr-1"></i> Dashboard </a>
        </div> -->
    </div>
</div>
<body>

{% endblock content %}

src/portal/investor/templates/investor/project_detail.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Candidate {{ object.user }} {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

                {# IMAGE DIV #}
                <div class="text-center">
                    {% if object.logo %}
                    <img class="rounded-circle" src="{{object.logo.url}}" height="150px"
                         alt="user-image">
                    {% else %}
                    <img class="rounded-circle" src="{% static 'core/images/logo_100.png' %}"
                         height="150px" alt="no-user-image">
                    {% endif %}
                </div>

                {# NAME AND OTHER #}


            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-8">

        <div class="card">
            <div class="card-body border-bottom">
                <p class="mb-0 card-title">Project Information</p>
            </div>
            <div class="card-body">
    <ul class="list-group p-4">
        <h6><li > Project Name     : {{object.name}}</li></h6>
        <h6><li > Category : {{object.category}}</li></h6>
        <h6><li > Website     : {{object.website}}</li></h6>
        <h6><li > Cro     : {{object.cro}}</li></h6>
        <h6><li > Registration Number     : {{object.registration_number}}</li></h6><hr>
    </ul>
            </div>
        </div>

    </div>

    <div class="col-4">
        <div class="card">
            <div class="card-body border-bottom">
                <p class="mb-0 card-title">Action</p>
                <p class="mb-0 card-title-desc">Sell Your Share or delete your Project
            </div>
            <div class="card-body">

                <a class="btn btn-success"
                   href="{% url 'investor:buy_share' object.pk %}">
                    <i class="fa fa-check-circle"></i> Buy Shares
                </a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <a href="{% url 'investor:project_list' %}"><b><i class="fa fa-arrow-left"></i></b> Back to
            Projects</a>
    </div>
</div>

{% endblock %}

src/portal/investor/templates/investor/share_detail.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}
<div class="row mb-2">
    <div class="col-lg-12">
        <h4>Share Details</h4>
        <hr>


        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-body">
                        {% if object_list %}

                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap table-hover">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Business Name</th>
                                    <th scope="col">Project Name</th>
                                    <th scope="col">Buyed Share</th>
                                    <th scope="col">Buyed Equity</th>
                                    <th scope="col">Is paid</th>
                                    <th scope="col">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in object_list %}
                                <tr>
                                    <td>
                                        <p class="mb-0">
                                            <b><a href="#">{{ object.share.project.business }}</a></b>
                                        </p>
                                    </td>
                                    <td>
                                        <p class="mb-0">
                                            <b><a href="#">{{ object.share.project }}</a></b>
                                        </p>
                                    </td>

                                    <td>
                                        <p class="mb-0">
                                            <b><a href="#">{{ object.value }}</a>
                                            </b>
                                    </td>
                                    <td>
                                        <p class="mb-0">
                                            <b><a href="#">{{ object.percentage_equity }}</a>
                                            </b>
                                    </td>
                                    <td>
                                        <p class="mb-0">
                                            {% if object.is_agree == True %}
                                            <i class="fa fa-check text-success"></i>
                                            {% else %}
                                            <i class="fa fa-times text-danger"></i>
                                            {% endif %}
                                        </p>

                                    </td>

                                    <td>
                                        <p class="mb-0">
                                            <a href="{% url 'investor:view_share' object.pk %}"
                                               class="btn btn-success btn-sm">view</a>
                                    </td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>

                        {% else %}
                        <p class="text-danger">
                            <b><i class="fa fa-exclamation-circle"></i> No Project found.</b>
                        </p>
                        {% endif %}

                    </div>
                </div>
                <!-- <div class="col-sm-6">
                    <a href=""
                       class="btn text-muted d-none d-sm-inline-block btn-link">
                        <i class="mdi mdi-arrow-left mr-1"></i> Dashboard </a>
                </div> -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/portal/investor/templates/investor/share_view_detail.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-lg-12">
        <h4>Share Detail</h4>
        <hr>

        <div class="table-responsive">

            <table class="table project-list-table table-nowrap table-centered table-borderless">
                <tbody>
                <thead class="thead-light">
                <tr>
                    <th scope="col">Business Name</th>
                    <th scope="col">Project name</th>
                    <th scope="col">Share Status</th>
                    <th scope="col">Share Equity</th>
                    <th scope="col">Share Value</th>
                    <th scope="col">Is Paid</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Updated At</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tr>
                    <td>
                        <p class="mb-0">
                            {{ object.share.project.business }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.share.project }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.share.status }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.percentage_equity }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.value }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {% if object.is_agree == True %}
                            <i class="fa fa-check text-success"></i>
                            {% else %}
                            <i class="fa fa-times text-danger"></i>
                            {% endif %}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.created_at }}
                        </p>

                    </td>
                    <td>
                        <p class="mb-0">
                            {{ object.updated_at }}
                        </p>

                    </td>
                    <td>
                     {% if object.is_agree == True %}
                        <a href="{% url 'investor:investor_shares' object.pk  %}"
                           class="btn btn-success btn-sm ">Sell Shares</a>
                    </td>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
        <div>
            <div>
                <a href="{% url 'investor:share_detail'  %}"
                   class="btn text-muted d-none d-sm-inline-block btn-link">
                    <i class="mdi mdi-arrow-left mr-1"></i> Dashboard </a>

            </div>
        </div>
    </div>
</div>

{% endblock %}

src/portal/investor/templates/investor/success.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    body {
    background: dark;
    margin-top: 120px;
    margin-bottom: 120px;
}


</style>
<div class="row justify-content-center">

    <div class="col-8">
        <div class="text-center">
            <h4>Your Have been successfully Buyed shares</h4>

        </div>




                <div class="row m-5 justify-content-center">
                    <a href="{% url 'investor:project_list' %}"> Go Back</a>
                </div>



            </div>
        </div>

