core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('src.website.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('accounts/', include('src.accounts.urls')),
                  path('business/', include('src.portal.business.urls')),
                  path('investor/', include('src.portal.investor.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path, include

from src.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('cross-auth/', views.CrossAuth.as_view(), name='cross_auth'),
    path('identification/', views.IdentificationCheck.as_view(), name='identification_check'),
    path('business-confirmation/', views.BusinessUserConfirm.as_view(), name='business_complete_zone'),
    path('investor-confirmation/', views.InvestorUserConfirm.as_view(), name='investor_complete_zone'),
    path('update_profile/', views.UserUpdateView.as_view(), name='update_profile'),
    path('investor_update_profile/', views.InvestorUpdateView.as_view(), name='investor_update_profile'),

]

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- BootStrap Link -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/animate.css' %}">

    <!-- Icon Link -->
    <link rel="stylesheet" href="{% static 'website/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/line-awesome.min.css' %}">

    <!-- Plugings Link -->
    <link rel="stylesheet" href="{% static 'website/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/odometer.css' %}">

    <!-- Custom Link -->
    <link rel="stylesheet" href="{% static 'website/css/main.css' %}">
    <link rel="shortcut icon" href="{% static 'website/images/favicon.png' %}" type="image/x-icon">

    <title>Digital - Investment Business </title>

</head>

<body>
    {% include 'core/include/header.html' %}

    <div class="preloader">
        <div class="preinnner">
            <div class="ring"></div>
            <div class="ring"></div>
            <div class="ring"></div>
        </div>
    </div>
    <div class="overlay"></div>

    {% block content %}
   
    {% endblock content %}

    {% include 'core/include/footer.html' %}



    

    <a href="#0" class="scrollToTop"><i class="las la-rocket"></i></a>
    <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="{% static 'website/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'website/js/slick.min.js' %}"></script>
    <script src="{% static 'website/js/nice-select.js' %}"></script>
    <script src="{% static 'website/js/odometer.min.js' %}"></script>
    <script src="{% static 'website/js/viewport.jquery.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

<!-- Mirrored from template.viserlab.com/digihyip/demo/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Jun 2022 06:01:23 GMT -->
</html>

templates/core/base_auth.html
{% load static %}
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">


<!-- Mirrored from themesbrand.com/velzon/html/default/auth-signup-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Mar 2022 12:37:31 GMT -->
<head>

        <meta charset="utf-8" />
        <title>Register Here</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'accounts/images/favicon.ico' %}">

        <!-- Layout config Js -->
        <script src="{% static 'accounts/js/layout.js' %}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'accounts/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'accounts/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'accounts/css/app.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'accounts/css/custom.min.css' %}" rel="stylesheet" type="text/css" />


    </head>
<body>
{% block auth_content %}

{% endblock auth_content %}


        <!-- JAVASCRIPT -->
        <script src="{% static 'accounts/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'accounts/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'accounts/libs/node-waves/waves.min.js' %}"></script>
        <script src="{% static 'accounts/libs/feather-icons/feather.min.js' %}"></script>
        <script src="{% static 'accounts/js/pages/plugins/lord-icon-2.1.0.js' %}"></script>
        <script src="{% static 'accounts/js/plugins.js' %}"></script>

        <!-- particles js -->
        <script src="{% static 'accounts/libs/particles.js/particles.js' %}"></script>
        <!-- particles app js -->
        <script src="{% static 'accounts/js/pages/particles.app.js' %}"></script>
        <!-- validation init -->
        <script src="{% static 'accounts/js/pages/form-validation.init.js' %}"></script>
    </body>


<!-- Mirrored from themesbrand.com/velzon/html/default/auth-signup-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Mar 2022 12:37:31 GMT -->
</html>

templates/core/base_dashboard.html
{% load static %}
{#{% load notifications_tags %}#}
<!doctype html>
<html lang="en">
<head>
    <link rel="icon" href="{% static "core/images/logo_100.png" %}">
    <title>App |

        {# BASE HALF TITLE #}
        {% block base_title %}{% endblock %}
        {# --------------- #}

    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
{#    <link rel="stylesheet" href="{% static 'core/css/app-dark.min.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'core/css/bootstrap-dark.min.css' %}">#}

    <link rel="stylesheet" href="{% static 'core/css/app.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'core/css/icons.min.css' %}">


    {# BASE LINKS THAT ARE REQUIRED FOR CERTAIN PAGE ------------- #}
    {% block base_links %}

    {% endblock %}
    {# ----------------------------------------------------------- #}

</head>
<body data-topbar="dark" data-layout="horizontal">

<!-- Begin page -->
<div id="layout-wrapper">

    {# BASE TOP NAVIGATION PANEL AREA -------------------------- #}
    {% block base_top_nav %}
        {% include 'core/base_head.html' %}
    {% endblock %}
    {# --------------------------------------------------------- #}

    {% block dont_include_details %}

        <div class="main-content">

            <div class="page-content mt-4">
                <div class="container-fluid mt-5">

                    <div class="row">
                        {% include 'core/include/messages.html' %}
                    </div>

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-flex align-items-center justify-content-between">
                                <h4 class="mb-0 font-size-18">

                                    {% block page_heading %} {% endblock %}</h4>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <div class="row">
                        <div class="col-12">
                            {% block content %}

                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}
</div>

<script src="{% static 'core/libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/libs/metismenu/metisMenu.min.js' %}"></script>
<script src="{% static 'core/libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'core/libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'core/js/app.js' %}"></script>

{#<script src="{% static 'js/notify.js' %}" type="text/javascript"></script>#}
{#{% register_notify_callbacks callbacks='fill_notification_badge,my_special_notification_callback' %}#}


{# BASE INTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
{% block base_internal_scripts %}

{% endblock %}
{# -------------------------------------------------------- #}

</body>
</html>


{# BASE EXTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
{% block base_external_scripts %}

{% endblock %}
{# -------------------------------------------------------- #}

templates/core/base_head.html
{% load static %}
{#{% load notifications_tags %}#}

{# MAIN HEADER ------------------------------------------------------------------------------------------------------ #}
<header id="page-topbar">
    <div class="navbar-header">

        {# LEFT HEAD ------------------- #}
        <div class="d-flex">
            <div class="navbar-brand-box">
                <a href="/" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="17">
                    </span>
                </a>

                <a href="/" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="19">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        {# RIGHT HEAD ------------------ #}
        <div class="d-flex">

            {# FULL_SCREEN -------------------------------------------------------- #}

            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            {# NOTIFICATIONS ------------------------------------------------------ #}

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge badge-danger badge-pill">
                        1
{#                        % live_notify_badge %}#}
                    </span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="small"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <div id="notify_me_now">

                        </div>
                        <div class="p-2 border-top text-center">
                            <button class="btn text-primary small">
                                <i class="mdi mdi-arrow-right-circle mr-1"></i> Mark All as Read
                            </button>
                        </div>
                    </div>
                </div>

            </div>

            {# USER ONLINE -------------------------------------------------------- #}

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

<!--                    {% if request.user.profile_image %}-->
<!--                        <img class="rounded-circle header-profile-user" src="{% static 'images/user.png' %}" alt="Header Avatar">-->
<!--                    {% else %}-->
<!--                         <img class="rounded-circle header-profile-user" src="{% static 'images/user.png' %}">-->
<!--                    {% endif %}-->


                    <span class="d-none d-xl-inline-block ml-1">{{ request.user.username }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                
                <div class="dropdown-menu dropdown-menu-right">
                    
                    {% if user.is_investor %}
                    <a class="dropdown-item" href="{% url 'accounts:investor_update_profile' %}">
                        <i class="bx bx-user font-size-16 align-middle mr-1"></i> Profile
                    </a>
                    {% elif  request.user.is_business %}
                    <a class="dropdown-item" href="{% url 'accounts:investor_update_profile' %}">
                        <i class="bx bx-user font-size-16 align-middle mr-1"></i> Profile
                    </a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item d-block text-danger" href="#">
                        {#                        <span class="badge badge-success float-right">11</span>#}
                        <i class="bx bx-wrench font-size-16 align-middle mr-1"></i> Settings
                    </a>
                    <a class="dropdown-item" href="{% url 'account_email' %}">
                        <i class="bx bxl-telegram font-size-16 align-middle mr-1"></i> Email accounts
                    </a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">
                        <i class="bx bx-lock-open font-size-16 align-middle mr-1"></i>Password Change
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-primary" href="{% url 'account_logout' %}">
                        <i class="bx bx-power-off font-size-16 align-middle mr-1"></i> Logout
                    </a>
                </div>
            </div>

            {# USER INFO ---------------------------------------------------------- #}

        </div>

    </div>
</header>

{# SUB HEADER ------------------------------------------------------------------------------------------------------- #}
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">

                    {% if request.user.is_authenticated %}
                        {% if request.user.is_business %}
                            {% include 'core/include/business_header.html' %}
                        {% else %}
                            {% include 'core/include/investor_header.html' %}
                        {% endif %}
                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>
</div>