core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('src.website.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('accounts/', include('src.accounts.urls')),
                  path('business/', include('src.portal.business.urls')),
                  path('investor/', include('src.portal.investor.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portal/business/urls.py
from django.urls import path, include

from . import views

app_name = 'business'

urlpatterns = [
    path('dashboard/', views.BusinessDashboard.as_view(), name='dashboard'),
    path('project-list/', views.ProjectListView.as_view(), name='project_list'),
    path('project-detail<str:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('project-create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('project-update/<str:pk>/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('project-delete/<str:pk>/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<str:pk>/shares/', views.ProjectShareView.as_view(), name='project_share'),
    path('project-Shares-list/', views.SharesListView.as_view(), name='shares'),
    path('project-shares-update/<str:pk>/<str:project>/', views.ProjectShareUpdate.as_view(), name='shares_update'),
    path('project-share-delete/<str:pk>/<str:project>/', views.ProjectShareDelete.as_view(), name='shares_delete'),
    path('project-investors/', views.ShareInvestors.as_view(), name='project_investor'),
    path('investor-detail/<str:pk>', views.ShareInvestorDetailView.as_view(), name='investor_detail'),
    path('money-flow/<str:pk>/', views.MoneyFLowView.as_view(), name='money_flow'),
    path('payments/', views.PaymentListView.as_view(), name='payment')

]

src/portal/business/models.py
from django.db import models

# Create your models here.
from src.accounts.models import User


class Category(models.Model):
    title = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


filling_status = (
    ('True', u'Yes'),
    ('False', u'No')
)


class Business(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    business_name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='business/profile/')
    website = models.CharField(max_length=200, null=True, blank=True)
    status = models.BooleanField(default=False)
    cro = models.CharField(max_length=200)
    registration_number = models.CharField(max_length=200)
    registration_date = models.DateTimeField(null=True, blank=False)
    mandatory_filling = models.CharField(choices=filling_status, max_length=20)
    phone_no = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.business_name


class Investor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='investor/profiles')
    nationality = models.CharField(max_length=200)
    id_card = models.CharField(max_length=100)
    phone_no = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Project(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='projects/')
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    cro = models.CharField(max_length=200)
    registration_number = models.CharField(max_length=200)
    registration_date = models.DateTimeField(null=True, blank=False)
    website = models.CharField(max_length=120, null=True, blank=True)
    account_name = models.CharField(max_length=100)
    bank_name = models.CharField(max_length=100)
    iban_no = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Shares(models.Model):
    choices = (
        ('equity', 'Equity'),)
    project = models.ForeignKey(Project, on_delete=models.CASCADE,related_name='shared_project')
    status = models.CharField(choices=choices, max_length=20, default='equity')
    value = models.PositiveIntegerField(default=0)
    percentage_equity = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    sell_equity = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)


class Project_Investor(models.Model):
    investor = models.ForeignKey(Investor, on_delete=models.CASCADE)
    share = models.ForeignKey(Shares, on_delete=models.CASCADE)
    value = models.PositiveIntegerField(default=0)
    percentage_equity = models.DecimalField(max_digits=4,decimal_places=2,default=0)
    is_agree=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.investor.user.username


class Payment(models.Model):
    payment_id = models.CharField(max_length=200,unique=True)

    project_investor = models.ForeignKey(Project_Investor, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.IntegerField()

    def __str__(self):
        return self.payment_id
        
class InvestorShare(models.Model):
    project_investor = models.ForeignKey(Project_Investor, on_delete=models.CASCADE)
    value = models.PositiveIntegerField(default=0)
    percentage_equity = models.DecimalField(max_digits=4,decimal_places=2,default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.project_investor.investor.user.username}'

class MoneyFlow(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    project_investor = models.ForeignKey(Project_Investor, on_delete=models.CASCADE, null=True, blank=True)
    business_profit_project = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    business_loss_project = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    investor_profit = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    investor_loss = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    monthly_cost = models.IntegerField(default=0)
    monthly_earning = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project.name

src/portal/business/views.py
from decimal import Decimal

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.forms import ModelForm
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.base import View

from src.accounts.decorators import business_required
from src.portal.business.bll import money_flow
from src.portal.business.filter import ProjectFilter
from src.portal.business.models import Business, Project, Investor, Project_Investor, Shares, MoneyFlow, Payment


@method_decorator(business_required, name='dispatch')
class BusinessDashboard(TemplateView):
    template_name = 'business/dashboard.html'

    def get_context_data(self, **kwargs):
        business_profit_project, business_loss_project, investor_profit, investor_loss = money_flow(self,
                                                                                                    request=self.request)
        context = super(BusinessDashboard, self).get_context_data(**kwargs)
        project = Project.objects.filter(business__user=self.request.user)
        context['investor_count'] = Investor.objects.all().count()
        context['project_count'] = project.count()
        context['project_investor'] = Project_Investor.objects.filter(share__project__business__user=self.request.user). \
                                          order_by('created_at').all()[:5]
        context['Buy_Shares'] = Project_Investor.objects.filter(share__project__business__user=self.request.user). \
                                    order_by('created_at').all()[:5].count()
        context['projects'] = Project.objects.filter(business__user=self.request.user).all()[:5]
        context['business_profit'] = business_profit_project
        context['business_loss'] = business_loss_project
        context['investor_profit'] = investor_profit
        context['investor_loss'] = investor_loss
        return context


@method_decorator(business_required, name='dispatch')
class ProjectListView(ListView):
    model = Project
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        user = self.request.user
        object_list = Project.objects.select_related('business').filter(business__user=user)
        filter_form = ProjectFilter(self.request.GET, object_list)
        paginator = Paginator(filter_form.qs, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['form'] = filter_form.form
        context['object_list'] = page_obj
        return context


@method_decorator(business_required, name='dispatch')
class ProjectDetailView(DetailView):
    model = Project
    context_object_name = 'object'
    template_name = 'business/project_detail.html'

    def get_queryset(self):
        user = self.request.user
        return Project.objects.select_related('business').filter(business__user=user)


@method_decorator(business_required, name='dispatch')
class ProjectCreateView(CreateView):
    model = Project
    fields = ['name', 'logo', 'category', 'website', 'cro', 'registration_number', 'account_name', 'bank_name',
              'iban_no']
    success_url = reverse_lazy('business:dashboard')

    def form_valid(self, form):
        business = Business.objects.get(user=self.request.user)
        form.instance.business = business
        messages.success(self.request, 'Project Created Successfully')
        return super(ProjectCreateView, self).form_valid(form)


@method_decorator(business_required, name='dispatch')
class ProjectUpdateView(UpdateView):
    model = Project
    fields = ['name', 'logo', 'category', 'website']
    success_url = reverse_lazy('business:dashboard')


@method_decorator(business_required, name='dispatch')
class ProjectDeleteView(DeleteView):
    template_name = 'business/project_delete.html'
    model = Project
    success_url = reverse_lazy('business:dashboard')

    def get_queryset(self):
        user = self.request.user
        return Project.objects.select_related('business').filter(business__user=user)


class ProjectShareForm(ModelForm):
    class Meta:
        model = Shares
        fields = ['status', 'value', 'percentage_equity']


@method_decorator(business_required, name='dispatch')
class ProjectShareView(View):
    def get(self, request, pk):
        form = ProjectShareForm
        context = {'form': form}
        return render(request, 'business/project_investor_create.html', context)

    def post(self, request, pk):
        user_value = request.POST.get('value')
        percentage_equ = request.POST.get('percentage_equity')
        project = Project.objects.get(id=pk)
        project_share, created = Shares.objects.get_or_create(
            project=project
        )
        project_share.value = int(project_share.value) + int(user_value)
        project_share.percentage_equity = float(project_share.percentage_equity) + float(percentage_equ)
        project_share.save()
        messages.success(request, f'You request For Selling Share is Posted')
        return redirect('business:project_list')


@method_decorator(business_required, name='dispatch')
class ProjectShareUpdate(UpdateView):
    model = Shares
    fields = ['status', 'value', 'percentage_equity']
    template_name = 'business/project_investor_create.html'
    success_url = reverse_lazy('business:project_list')


@method_decorator(business_required, name='dispatch')
class ProjectShareDelete(DeleteView):
    model = Shares
    template_name = 'business/project_share_delete.html'
    success_url = reverse_lazy('business:project_list')


@method_decorator(business_required, name='dispatch')
class SharesListView(ListView):
    model = Shares
    template_name = 'business/shares_list.html'

    def get_queryset(self):
        return Shares.objects.filter(project__business__user=self.request.user)


#
@method_decorator(business_required, name='dispatch')
class ShareInvestors(ListView):
    model = Project_Investor
    template_name = 'business/project_investor.html'

    def get_queryset(self):
        return Project_Investor.objects.filter(Q(share__project__business__user=self.request.user) & Q(is_agree=True))


class ShareInvestorDetailView(DetailView):
    model = Project_Investor
    context_object_name = 'object'
    template_name = 'business/investor_Detail.html'

    def get_context_data(self, **kwargs):
        context = super(ShareInvestorDetailView, self).get_context_data(**kwargs)
        investor = Investor.objects.filter(id=self.kwargs['pk'])
        project_share = Project_Investor.objects.filter(Q(investor=investor) & Q(is_agree=True))
        context['projects'] = project_share
        return context


class MoneyFLowForm(ModelForm):
    class Meta:
        model = MoneyFlow
        fields = ['monthly_cost', 'monthly_earning']


@method_decorator(business_required, name='dispatch')
class MoneyFLowView(View):
    def get(self, request, pk):
        form = MoneyFLowForm
        context = {'form': form}
        return render(request, 'business/moneyflow.html', context)

    def post(self, request, pk):
        project = Project.objects.get(id=pk)
        project_investor = Project_Investor.objects.filter(share__project=project).first()
        cost = int(request.POST.get('cost'))
        earning = int(request.POST.get('earning'))
        if project_investor:
            money_flow, created = MoneyFlow.objects.get_or_create(project=project, project_investor=project_investor)
            investor_equity = Decimal(project_investor.percentage_equity)
            if int(earning) >= int(cost):
                profit = Decimal(earning) - Decimal(cost)

                print("Profit ", profit)
                money_flow.business_profit_project = (Decimal(profit) / Decimal(earning)) * 100
                print("business ", money_flow.business_profit_project)
                money_flow.business_loss_project = 0
                money_flow.investor_loss = 0
                inves_profit = (Decimal(investor_equity) * Decimal(earning)) / 100
                print("invest ", inves_profit)
                money_flow.investor_profit = Decimal(inves_profit) / Decimal(earning) * 100
                print("invest_prof ", money_flow.investor_profit)
                money_flow.monthly_cost = int(cost)
                money_flow.monthly_earning = int(earning)
                print("earning ", earning)
            elif int(earning) <= int(cost):
                profit = Decimal(cost) - Decimal(earning)
                money_flow.business_profit_project = 0
                money_flow.investor_profit = 0
                money_flow.business_loss_project = (Decimal(profit) / Decimal(cost)) * 100
                inves_profit = (Decimal(investor_equity) * Decimal(earning)) / 100
                money_flow.investor_loss = (Decimal(inves_profit) / Decimal(earning)) * 100
                money_flow.monthly_cost = int(cost)
                money_flow.monthly_earning = int(earning)
            money_flow.save()
            return redirect('business:project_list')
        else:
            money_flow, created = MoneyFlow.objects.get_or_create(project=project)
            if int(earning) >= int(cost):
                profit = Decimal(earning) - Decimal(cost)
                money_flow.business_profit_project = (Decimal(profit) / Decimal(earning)) * 100
                money_flow.business_loss_project = 0
                money_flow.monthly_cost = int(cost)

src/portal/business/templates/business/dashboard.html
{% extends 'core/base_dashboard.html' %}
{% load static %}
{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<body>


<div class="row">
    <div class="col-sm-6">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class=" h2 text-primary mb-0"></i>
                    </div>
                    <div class="media-body">
                        <canvas id="polar-chart" style="width:100%;max-width:600px;height:320px"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3 align-self-center">
                        <i class=" h2 text-primary mb-0"></i>
                    </div>
                    <div class="media-body">
                        <canvas id="myChart" style="width:100%;max-width:600px;height:320px"></canvas>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--    <div class="col-sm-3">-->
    <!--        <div class="card mini-stats-wid">-->
    <!--            <div class="card-body">-->
    <!--                <div class="media">-->
    <!--                    <div class="mr-3 align-self-center">-->
    <!--                        <i class="bx bx-import h2 text-success mb-0"></i>-->
    <!--                    </div>-->
    <!--                    <div class="media-body">-->
    <!--                        <p class="text-muted mb-2">Investors</p>-->
    <!--                        <h5 class="mb-0">-->
    <!--                            {{investor_count}}-->
    <!--                        </h5>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--            </div>-->
    <!--        </div>-->
    <!--    </div>-->
<!--        <div class="col-sm-3">-->
<!--            <div class="card mini-stats-wid">-->
<!--                <div class="card-body">-->
<!--                    <div class="media">-->
<!--                        <div class="mr-3 align-self-center">-->
<!--                            <i class="bx bx-export h2 text-danger mb-0"></i>-->
<!--                        </div>-->
<!--                        <div class="media-body">-->
<!--                            <p class="text-muted mb-2">Profit</p>-->
<!--                            <h6 class="mb-0">-->
<!--                                Business Profit : {{ business_profit }}-->
<!--                                Investor Profit : {{ investor_profit }}-->
<!--                            </h6>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
    <!--    <div class="col-sm-3">-->
    <!--        <div class="card mini-stats-wid">-->
    <!--            <div class="card-body">-->
    <!--                <div class="media">-->
    <!--                    <div class="mr-3 align-self-center">-->
    <!--                        <i class="bx bxl-telegram h2 text-primary mb-0"></i>-->
    <!--                    </div>-->
    <!--                    <div class="media-body">-->
    <!--                        <p class="text-muted mb-2">-</p>-->
    <!--                        <h6 class="mb-0">-->
    <!--                             Business Loss : {{ business_loss }}-->
    <!--                            Investor Loss : {{ investor_loss }}-->
    <!--                        </h6>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--            </div>-->
    <!--        </div>-->
    <!--    </div>-->
</div>


<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="border-bottom card-body">
                <p class="card-title mb-0">New Projects</p>
            </div>
            <div class="card-body">
                {% if projects %}

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-hover">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Project Name</th>
                            <th scope="col">Project Category</th>
                            <th scope="col">Website</a></th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for object in projects %}
                        <tr>
                            <td>
                                <p class="mb-0">
                                    <b><a href="{% url 'business:project_detail' object.pk %}">{{ object.name }}</a></b>
                                </p>
                            </td>
                            <td>
                                <p class="mb-0">
                                    <b>{{ object.category }}</b>
                                </p>
                            </td>


                            <td><a href="{{object.website}}" target="_blank">{{ object.website }}</a></td>

                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                {% else %}
                <p class="text-danger">
                    <b><i class="fa fa-exclamation-circle"></i> No jobs found.</b>
                </p>
                {% endif %}

            </div>
        </div>

    </div>
    <div class="col-6">
        <div class="card">
            <div class="border-bottom card-body">
                <p class="card-title mb-0">Recently Buyed Shares</p>
            </div>
            <div class="card-body">
                {% if project_investor %}

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-hover">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Investor Name</th>
                            <th scope="col">Project Name</th>
                            <th scope="col">Buyed Shares</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for object in project_investor %}
                        <tr>
                            <td>
                                <p class="mb-0">
                                    <b><a href="{% url 'business:investor_detail' object.pk %">{{ object.investor }}</a></b>
                                </p>
                            </td>
                            <td>
                                <p class="mb-0">
                                    <b><a href="{% url 'business:project_detail' object.pk %}">{{ object.share.project }}</a></b>
                                </p>
                            </td>


                            <td>{{ object.value }}</td>

                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                {% else %}
                <p class="text-danger">
                    <b><i class="fa fa-exclamation-circle"></i> No jobs found.</b>
                </p>
                {% endif %}

            </div>
        </div>

    </div>
</div>
<script>
var xValues = ["Total Investors", "Total Projects","Share Holders"];
var yValues = [{{investor_count}},{{project_count}},{{Buy_Shares}}];
var barColors = [
  "#b91d47",
  "#00aba9",
  "#f1c40f",

];

new Chart("myChart", {
  type: "doughnut",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "Total Number of Investors Your Projects and Share Holders"
    }
  }
});



</script>
<script>
new Chart(document.getElementById("polar-chart"), {
    type: 'polarArea',
    data: {
      labels: ["Business Profit", "Business Loss", "Shareholders Profit", "Shareholders Profit",],
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ["#3e95cd","#3cba9f","#e8c3b9","#c45850"],
          data: [{{business_profit}},{{business_loss}},{{investor_profit}},{{investor_loss}}]
        }
      ]
    },
    options: {
      title: {
        display: true,
        text: 'Business and Shareholders loss or profit'
      }
    }
});
</script>
{% endblock %}



src/portal/business/templates/business/project_list.html
{% extends 'core/base_dashboard.html' %}
{% load widget_tweaks%}
{% load static %}

{% block base_title %} Projects {% endblock %}
{% block page_heading %} Project {% endblock %}

{% block content %}
             <div class="col-lg-12">
                <div class=" mb-2">
                    <div class="container video-content">
                        <div class="row">
                            <div class="col-md-12  text-center mt-20">
                                <form method="GET" class="hero__form v4 filter listing-filter">
                                    <div class="row">
                                        <div class="col-lg-7 col-md-12 ">
                                            <div class="input-search ">
                                                {% render_field form.name class='form-control'%}
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-md-12 pr-0">
                                            {% render_field form.category class='form-control' %}
                                        </div>


                                        <div class="col-lg-2 col-sm-12">
                                            <button class="btn btn-success" type="submit">Search</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<div class="row">
    <div class="col-12">

        <div class="card">

            <div class="card-body">
                {% if object_list %}

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-hover">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Website</th>
                            <th scope="col">Sell Shares</th>
                            <th scope="col">Calculate Profit</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                                <p class="mb-0">
                                    <a href="{% url 'business:project_detail' object.pk %}"><b>{{ object.name }}</b></a>
                                </p>
                            </td>
                            <td>
                                <p class="mb-0">
                                    <b>{{ object.category }}</b>
                                </p>
                            </td>

                            <td>
                                <p class="mb-0">
                                    <b><a href="{{object.website}}" target="_blank">{{ object.website }}</a>
                                    </b>
                            </td>
                            <p class="mb-0">
                                <td>
                            <p class="mb-0">
                                <a href="{% url 'business:project_share' object.pk %}"
                                   class="btn btn-success btn-sm">Sell</a>
                                </td>
                            <td>
                            <p class="mb-0">
                                <a href="{% url 'business:money_flow' object.pk %}"
                                   class="btn btn-success btn-sm">calculate</a>
                                </td>


                            <td>
                                <a href="{% url 'business:project_detail' object.pk %}">
                                    <b><i class="fa fa-eye"></i> </b>
                                </a>
                                <a href="{% url 'business:project_update' object.pk %}">
                                    <b><i class="fa fa-edit"></i> </b>
                                </a>
                                <a href="{% url 'business:project_delete' object.pk %}" class="text-danger">
                                    <b><i class="fa fa-trash"></i> </b>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                {% else %}
                <p class="text-danger">
                    <b><i class="fa fa-exclamation-circle"></i> No Project found.</b>
                </p>
                {% endif %}

            </div>
        </div>

    </div>
</div>

{% endblock %}